"""Candidate-specific RAG foundation for asses.ai (Phase 1: storage layer).

Public surface:
  models     -> RagDocument, SearchResult, SearchFilters, SOURCES, CHUNK_TYPES
  embeddings -> EmbeddingProvider, GeminiEmbeddingProvider, get_embedding_provider
  index      -> VectorStore, RedisVectorStore, InMemoryVectorStore,
                RagConfig, ensure_index, get_vector_store
  planner    -> QuestionPlan, InterviewState, CandidateContext,
                plan_next_question (no natural-language generation)

Importing this package performs no network I/O.
See server/RAG/README.md for schema, env vars, and isolation guarantees.
"""

from .models import (
    CHUNK_TYPES,
    SOURCES,
    RagDocument,
    SearchFilters,
    SearchResult,
    check_candidates_match,
)
from .embeddings import (
    DEFAULT_DIMENSION,
    DEFAULT_MODEL,
    EmbeddingError,
    EmbeddingProvider,
    GeminiEmbeddingProvider,
    LocalEmbeddingProvider,
    get_embedding_provider,
)
from .index import (
    DimensionMismatchError,
    InMemoryVectorStore,
    RagConfig,
    RagUnavailableError,
    RedisVectorStore,
    VectorStore,
    build_index_fields,
    connect_redis,
    ensure_index,
    get_vector_store,
    has_vector_search,
    redis_has_search,
)
from .ingestion import (
    build_candidate_documents,
    chunk_github_repo,
    chunk_leetcode_stats,
    chunk_resume_text,
    ingest_candidate_profile,
    normalize_leetcode_stats,
    parse_repo_slug,
    split_markdown_sections,
    split_resume_sections,
    window_text,
)
from .retrieval import (
    RRF_K,
    STOPWORDS,
    apply_diversity,
    extract_terms,
    format_context,
    retrieve_candidate_context,
    rrf_fuse,
)
from .prompts import (
    EVIDENCE_CHARS,
    HISTORY_TURNS,
    NO_EVIDENCE_MARKER,
    build_intro_prompt,
    build_technical_prompt,
    derive_interview_state,
    format_evidence,
    history_window,
)
from .planner import (
    INTENTS,
    CandidateContext,
    HeuristicPlanner,
    InterviewState,
    LLMPlanner,
    PlannerError,
    ProjectEvidence,
    QuestionPlan,
    TopicEvidence,
    context_from_profile,
    plan_next_question,
)
from .adaptive import (
    AdaptiveState,
    AnswerAssessment,
    adaptive_prompt_block,
    assess_answer,
    closing_plan,
    fingerprint,
    load_adaptive_state,
    record_asked,
    to_planner_state,
    update_after_answer,
)
from .evaluation import (
    DIMENSIONS,
    DimensionScore,
    EvaluationReport,
    EvidenceItem,
    build_evaluation_inputs,
    evaluate_interview,
    heuristic_report,
    render_feedback,
)

__all__ = [
    "CHUNK_TYPES",
    "SOURCES",
    "RagDocument",
    "SearchFilters",
    "SearchResult",
    "check_candidates_match",
    "DEFAULT_DIMENSION",
    "DEFAULT_MODEL",
    "EmbeddingError",
    "EmbeddingProvider",
    "GeminiEmbeddingProvider",
    "LocalEmbeddingProvider",
    "get_embedding_provider",
    "DimensionMismatchError",
    "InMemoryVectorStore",
    "RagConfig",
    "RagUnavailableError",
    "RedisVectorStore",
    "VectorStore",
    "build_index_fields",
    "connect_redis",
    "ensure_index",
    "get_vector_store",
    "has_vector_search",
    "redis_has_search",
    "build_candidate_documents",
    "chunk_github_repo",
    "chunk_leetcode_stats",
    "chunk_resume_text",
    "ingest_candidate_profile",
    "normalize_leetcode_stats",
    "parse_repo_slug",
    "split_markdown_sections",
    "split_resume_sections",
    "window_text",
    "RRF_K",
    "STOPWORDS",
    "apply_diversity",
    "extract_terms",
    "format_context",
    "retrieve_candidate_context",
    "rrf_fuse",
    "EVIDENCE_CHARS",
    "HISTORY_TURNS",
    "NO_EVIDENCE_MARKER",
    "build_intro_prompt",
    "build_technical_prompt",
    "derive_interview_state",
    "format_evidence",
    "history_window",
    "sanitize_untrusted",
    "INTENTS",
    "CandidateContext",
    "HeuristicPlanner",
    "InterviewState",
    "LLMPlanner",
    "PlannerError",
    "ProjectEvidence",
    "QuestionPlan",
    "TopicEvidence",
    "context_from_profile",
    "plan_next_question",
    "AdaptiveState",
    "AnswerAssessment",
    "adaptive_prompt_block",
    "assess_answer",
    "closing_plan",
    "fingerprint",
    "load_adaptive_state",
    "record_asked",
    "to_planner_state",
    "update_after_answer",
    "DIMENSIONS",
    "EvidenceItem",
    "DimensionScore",
    "EvaluationReport",
    "build_evaluation_inputs",
    "evaluate_interview",
    "heuristic_report",
    "render_feedback",
]
